### PR TITLE
Integrator Argument Passing

### LINKED ISSUE #5: Integrator Settings
We need to enable passing other settings to the integrator. I've noticed in some cases that the integrator will die when doing something like setting the maximum step size to a much smaller size works. 

```
import numpy as np
import matplotlib.pyplot as plt
import rsf

model = rsf.RateState()

# Set model initial conditions
model.mu0 = 0.6 # Friction initial (at the reference velocity)
model.a = 0.007 # Empirical coefficient for the direct effect
model.b = 0.003 # Empirical coefficient for the evolution effect
model.dc = 100. # Critical slip distance
model.k = 0.00128 # Normalized System stiffness (friction/micron)
model.v = 300. # Initial slider velocity, generally is vlp(t=0)
model.vref = 300. # Reference velocity, generally vlp(t=0)
model.stateLaw = rsf.dieterichState # Which state relation we want to use

model.model_time = np.arange(0,450.01,0.01)

lp_velocity = 300* np.ones_like(model.model_time)
lp_velocity[10*100:12*100] = -300. 
lp_velocity[12*100:110.5*100] = 0.

# Set the model load point velocity, must be same shape as model.model_time
model.loadpoint_velocity = lp_velocity

# Run the model!
results = model.solve()

# Make the phase plot
model.phasePlot()

# Make a plot in displacement
model.dispPlot()

# Make a plot in time
model.timePlot()
```

### PR DESCRIPTION
**Pull request by jrleeman**
Allows passing of arguments to the integrator through the solve method. This is useful for things like setting the max step size (hmax) on problems that are particularly unstable. Resolves #5

### CODE REVIEW

**Comment by dopplershift** [comment]
My only question would be whether you still want `abserr` and `relerr` to be attributes on the class, or whether they should go through the same mechanism. You could set defaults if they're not passed in:

``` python
odeint_kwargs = dict(rtol=1e-12, atol=1e-12)
odeint_kwargs.update(kwargs)

si.odenit(..., **odeint_kwargs)
```
So the args start with the defaults, then are overridden by any that are passed in.

**Comment by jrleeman** [comment]
Ah. I was wondering what the best way to handle that is. I implemented it in the last push. Also fixed some of my bad spacing issues. How does this look?

**Comment by dopplershift** [comment]
Looks like someone pep8/flake8 -ed the code. :)

Everything looks good to me.

**Comment by jrleeman** [comment]
Yeah, I was bad about that. Will have to do some more cleaning as things get finalized. Some one the lines are pushing 110 chars.

**Comment by dopplershift** [comment]
I extended the limit to 90/95 characters in my projects, though I try to keep shorter.

**Pull request merged**
